[project]
name = "ffxiv-gear-slicer"
version = "0.1.0"
description = "FFXIV gear segmentation (head/upper/lower/shoes/hands)"
authors = [
    {name = "ricterzheng",email = "ricterzheng@tencent.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "torch (>=2.9.1,<3.0.0)",
    "torchvision (>=0.24.1,<0.25.0)",
    "transformers (>=4.57.3,<5.0.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "sam2 (>=1.1.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
